/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games/index'
import { Route as PlayerUpdateRouteImport } from './routes/player/update'
import { Route as PlayerCreateRouteImport } from './routes/player/create'
import { Route as RoomRoomRoomCodeRouteImport } from './routes/room/room.$roomCode'
import { Route as RoomActionsJoinRouteImport } from './routes/room/actions.join'
import { Route as RoomActionsCreateRouteImport } from './routes/room/actions.create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerUpdateRoute = PlayerUpdateRouteImport.update({
  id: '/player/update',
  path: '/player/update',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerCreateRoute = PlayerCreateRouteImport.update({
  id: '/player/create',
  path: '/player/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomRoomCodeRoute = RoomRoomRoomCodeRouteImport.update({
  id: '/room/room/$roomCode',
  path: '/room/room/$roomCode',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomActionsJoinRoute = RoomActionsJoinRouteImport.update({
  id: '/room/actions/join',
  path: '/room/actions/join',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomActionsCreateRoute = RoomActionsCreateRouteImport.update({
  id: '/room/actions/create',
  path: '/room/actions/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/player/create': typeof PlayerCreateRoute
  '/player/update': typeof PlayerUpdateRoute
  '/games': typeof GamesIndexRoute
  '/room/actions/create': typeof RoomActionsCreateRoute
  '/room/actions/join': typeof RoomActionsJoinRoute
  '/room/room/$roomCode': typeof RoomRoomRoomCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/player/create': typeof PlayerCreateRoute
  '/player/update': typeof PlayerUpdateRoute
  '/games': typeof GamesIndexRoute
  '/room/actions/create': typeof RoomActionsCreateRoute
  '/room/actions/join': typeof RoomActionsJoinRoute
  '/room/room/$roomCode': typeof RoomRoomRoomCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/player/create': typeof PlayerCreateRoute
  '/player/update': typeof PlayerUpdateRoute
  '/games/': typeof GamesIndexRoute
  '/room/actions/create': typeof RoomActionsCreateRoute
  '/room/actions/join': typeof RoomActionsJoinRoute
  '/room/room/$roomCode': typeof RoomRoomRoomCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/player/create'
    | '/player/update'
    | '/games'
    | '/room/actions/create'
    | '/room/actions/join'
    | '/room/room/$roomCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/player/create'
    | '/player/update'
    | '/games'
    | '/room/actions/create'
    | '/room/actions/join'
    | '/room/room/$roomCode'
  id:
    | '__root__'
    | '/'
    | '/player/create'
    | '/player/update'
    | '/games/'
    | '/room/actions/create'
    | '/room/actions/join'
    | '/room/room/$roomCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerCreateRoute: typeof PlayerCreateRoute
  PlayerUpdateRoute: typeof PlayerUpdateRoute
  GamesIndexRoute: typeof GamesIndexRoute
  RoomActionsCreateRoute: typeof RoomActionsCreateRoute
  RoomActionsJoinRoute: typeof RoomActionsJoinRoute
  RoomRoomRoomCodeRoute: typeof RoomRoomRoomCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/update': {
      id: '/player/update'
      path: '/player/update'
      fullPath: '/player/update'
      preLoaderRoute: typeof PlayerUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/create': {
      id: '/player/create'
      path: '/player/create'
      fullPath: '/player/create'
      preLoaderRoute: typeof PlayerCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/room/$roomCode': {
      id: '/room/room/$roomCode'
      path: '/room/room/$roomCode'
      fullPath: '/room/room/$roomCode'
      preLoaderRoute: typeof RoomRoomRoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/actions/join': {
      id: '/room/actions/join'
      path: '/room/actions/join'
      fullPath: '/room/actions/join'
      preLoaderRoute: typeof RoomActionsJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/actions/create': {
      id: '/room/actions/create'
      path: '/room/actions/create'
      fullPath: '/room/actions/create'
      preLoaderRoute: typeof RoomActionsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerCreateRoute: PlayerCreateRoute,
  PlayerUpdateRoute: PlayerUpdateRoute,
  GamesIndexRoute: GamesIndexRoute,
  RoomActionsCreateRoute: RoomActionsCreateRoute,
  RoomActionsJoinRoute: RoomActionsJoinRoute,
  RoomRoomRoomCodeRoute: RoomRoomRoomCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
